# Generated by Django 6.0.1 on 2026-04-28 13:00

import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalInventarioMantencion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Última Actualización')),
                ('producto', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, max_length=250)),
                ('unidad', models.CharField(max_length=50)),
                ('tipo_material', models.CharField(max_length=50)),
                ('tipo_compra', models.CharField(max_length=50)),
                ('codigo', models.CharField(db_index=True, max_length=50)),
                ('stock_actual', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=0)),
                ('stock_maximo', models.PositiveIntegerField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Producto Mantencion',
                'verbose_name_plural': 'historical Productos Mantecion',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='InventarioInformatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('producto', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, max_length=250)),
                ('unidad', models.CharField(max_length=50)),
                ('tipo_material', models.CharField(max_length=50)),
                ('tipo_compra', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('stock_actual', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=0)),
                ('stock_maximo', models.PositiveIntegerField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Producto TIC',
                'verbose_name_plural': 'Productos TIC',
            },
        ),
        migrations.CreateModel(
            name='InventarioMantencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('producto', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, max_length=250)),
                ('unidad', models.CharField(max_length=50)),
                ('tipo_material', models.CharField(max_length=50)),
                ('tipo_compra', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('stock_actual', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=0)),
                ('stock_maximo', models.PositiveIntegerField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Producto Mantencion',
                'verbose_name_plural': 'Productos Mantecion',
            },
        ),
        migrations.CreateModel(
            name='HistoricalInventarioInformatica',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Última Actualización')),
                ('producto', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, max_length=250)),
                ('unidad', models.CharField(max_length=50)),
                ('tipo_material', models.CharField(max_length=50)),
                ('tipo_compra', models.CharField(max_length=50)),
                ('codigo', models.CharField(db_index=True, max_length=50)),
                ('stock_actual', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=0)),
                ('stock_maximo', models.PositiveIntegerField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('categoria', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogo.subcategoria')),
            ],
            options={
                'verbose_name': 'historical Producto TIC',
                'verbose_name_plural': 'historical Productos TIC',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
