# Generated by Django 6.0.1 on 2026-06-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinventarioinformatica',
            name='responsable',
            field=models.CharField(choices=[('MANTENCIÓN', 'MANTENCIÓN'), ('AUXILIAR MANTENCIÓN', 'AUXILIAR MANTENCIÓN'), ('JEFE SERVICIOS GENERALES', 'JEFE SERVICIOS GENERALES'), ('OTRO', 'OTRO')], default='OTRO', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalinventarioinformatica',
            name='status_stock',
            field=models.CharField(choices=[('OK', 'OK'), ('REPOSICIÓN', 'REPOSICIÓN')], default='ACTIVO', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalinventariomantencion',
            name='responsable',
            field=models.CharField(choices=[('MANTENCIÓN', 'MANTENCIÓN'), ('AUXILIAR MANTENCIÓN', 'AUXILIAR MANTENCIÓN'), ('JEFE SERVICIOS GENERALES', 'JEFE SERVICIOS GENERALES'), ('OTRO', 'OTRO')], default='OTRO', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalinventariomantencion',
            name='status_stock',
            field=models.CharField(choices=[('OK', 'OK'), ('REPOSICIÓN', 'REPOSICIÓN')], default='ACTIVO', max_length=50),
        ),
        migrations.AddField(
            model_name='inventarioinformatica',
            name='responsable',
            field=models.CharField(choices=[('MANTENCIÓN', 'MANTENCIÓN'), ('AUXILIAR MANTENCIÓN', 'AUXILIAR MANTENCIÓN'), ('JEFE SERVICIOS GENERALES', 'JEFE SERVICIOS GENERALES'), ('OTRO', 'OTRO')], default='OTRO', max_length=100),
        ),
        migrations.AddField(
            model_name='inventarioinformatica',
            name='status_stock',
            field=models.CharField(choices=[('OK', 'OK'), ('REPOSICIÓN', 'REPOSICIÓN')], default='ACTIVO', max_length=50),
        ),
        migrations.AddField(
            model_name='inventariomantencion',
            name='responsable',
            field=models.CharField(choices=[('MANTENCIÓN', 'MANTENCIÓN'), ('AUXILIAR MANTENCIÓN', 'AUXILIAR MANTENCIÓN'), ('JEFE SERVICIOS GENERALES', 'JEFE SERVICIOS GENERALES'), ('OTRO', 'OTRO')], default='OTRO', max_length=100),
        ),
        migrations.AddField(
            model_name='inventariomantencion',
            name='status_stock',
            field=models.CharField(choices=[('OK', 'OK'), ('REPOSICIÓN', 'REPOSICIÓN')], default='ACTIVO', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalinventarioinformatica',
            name='ubicacion',
            field=models.CharField(blank=True, default='Bodega Mantención', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalinventariomantencion',
            name='ubicacion',
            field=models.CharField(blank=True, default='Bodega Mantención', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventarioinformatica',
            name='ubicacion',
            field=models.CharField(blank=True, default='Bodega Mantención', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventariomantencion',
            name='ubicacion',
            field=models.CharField(blank=True, default='Bodega Mantención', max_length=100),
        ),
    ]
