# Generated by Django 6.0.1 on 2026-04-21 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_rename_estado_historicalips_asignado_and_more'),
        ('inventario', '0002_rename_inventario_inventarioinformatica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinventariomantencion',
            name='categoria',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogo.subcategoria'),
        ),
        migrations.AlterField(
            model_name='inventariomantencion',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.subcategoria'),
        ),
    ]
