# Generated by Django 6.0.1 on 2026-06-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_historicalinventarioinformatica_responsable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinventarioinformatica',
            name='unidad',
            field=models.CharField(choices=[('UNIDAD', 'UNIDAD'), ('METRO', 'METRO'), ('CAJA', 'CAJA'), ('BOLSA', 'BOLSA'), ('LITRO', 'LITRO'), ('GALÓN', 'GALÓN'), ('PAR', 'PAR'), ('ROLLO', 'ROLLO'), ('PAQUETE', 'PAQUETE')], default='UNIDAD', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalinventariomantencion',
            name='unidad',
            field=models.CharField(choices=[('UNIDAD', 'UNIDAD'), ('METRO', 'METRO'), ('CAJA', 'CAJA'), ('BOLSA', 'BOLSA'), ('LITRO', 'LITRO'), ('GALÓN', 'GALÓN'), ('PAR', 'PAR'), ('ROLLO', 'ROLLO'), ('PAQUETE', 'PAQUETE')], default='UNIDAD', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventarioinformatica',
            name='unidad',
            field=models.CharField(choices=[('UNIDAD', 'UNIDAD'), ('METRO', 'METRO'), ('CAJA', 'CAJA'), ('BOLSA', 'BOLSA'), ('LITRO', 'LITRO'), ('GALÓN', 'GALÓN'), ('PAR', 'PAR'), ('ROLLO', 'ROLLO'), ('PAQUETE', 'PAQUETE')], default='UNIDAD', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventariomantencion',
            name='unidad',
            field=models.CharField(choices=[('UNIDAD', 'UNIDAD'), ('METRO', 'METRO'), ('CAJA', 'CAJA'), ('BOLSA', 'BOLSA'), ('LITRO', 'LITRO'), ('GALÓN', 'GALÓN'), ('PAR', 'PAR'), ('ROLLO', 'ROLLO'), ('PAQUETE', 'PAQUETE')], default='UNIDAD', max_length=50),
        ),
    ]
