# Generated by Django 6.0.1 on 2026-06-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_historicalinventarioinformatica_unidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinventarioinformatica',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalinventarioinformatica',
            name='ultima_salida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalinventariomantencion',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalinventariomantencion',
            name='ultima_salida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventarioinformatica',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventarioinformatica',
            name='ultima_salida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventariomantencion',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventariomantencion',
            name='ultima_salida',
            field=models.DateField(blank=True, null=True),
        ),
    ]
