# Generated by Django 6.0.1 on 2026-06-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_historicalinventarioinformatica_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinventarioinformatica',
            name='ubicacion',
            field=models.CharField(blank=True, default='Bodega Informática', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventarioinformatica',
            name='ubicacion',
            field=models.CharField(blank=True, default='Bodega Informática', max_length=100),
        ),
    ]
