# Generated by Django 6.0.1 on 2026-06-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_historicalinventarioinformatica_ubicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinventarioinformatica',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalinventariomantencion',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inventarioinformatica',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inventariomantencion',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
