# Generated by Django 6.0.1 on 2026-06-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_historicalinventarioinformatica_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinventarioinformatica',
            name='status_stock',
            field=models.CharField(choices=[('OK', 'OK'), ('REPOSICIÓN', 'REPOSICIÓN'), ('SOBRESTOCK', 'SOBRESTOCK')], default='ACTIVO', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalinventarioinformatica',
            name='tipo_compra',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalinventariomantencion',
            name='status_stock',
            field=models.CharField(choices=[('OK', 'OK'), ('REPOSICIÓN', 'REPOSICIÓN'), ('SOBRESTOCK', 'SOBRESTOCK')], default='ACTIVO', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventarioinformatica',
            name='status_stock',
            field=models.CharField(choices=[('OK', 'OK'), ('REPOSICIÓN', 'REPOSICIÓN'), ('SOBRESTOCK', 'SOBRESTOCK')], default='ACTIVO', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventarioinformatica',
            name='tipo_compra',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inventariomantencion',
            name='status_stock',
            field=models.CharField(choices=[('OK', 'OK'), ('REPOSICIÓN', 'REPOSICIÓN'), ('SOBRESTOCK', 'SOBRESTOCK')], default='ACTIVO', max_length=50),
        ),
    ]
