# Generated by Django 6.0.1 on 2026-06-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_alter_historicalinventarioinformatica_status_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinventariomantencion',
            name='tipo_compra',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inventariomantencion',
            name='tipo_compra',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
