# Generated by Django 6.0.1 on 2026-06-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_alter_historicalinventariomantencion_tipo_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinventarioinformatica',
            name='tipo_material',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalinventariomantencion',
            name='tipo_material',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inventarioinformatica',
            name='tipo_material',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inventariomantencion',
            name='tipo_material',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
