# Generated by Django 6.0.1 on 2026-06-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_alter_historicalinventarioinformatica_tipo_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinventariomantencion',
            name='status_stock',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('REPOSICIÓN', 'REPOSICIÓN'), ('SOBRESTOCK', 'SOBRESTOCK')], default='ACTIVO', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inventariomantencion',
            name='status_stock',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('REPOSICIÓN', 'REPOSICIÓN'), ('SOBRESTOCK', 'SOBRESTOCK')], default='ACTIVO', max_length=50, null=True),
        ),
    ]
