# Generated by Django 6.0.1 on 2026-02-25 13:39

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('establecimiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('establecimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='establecimiento.establecimiento', verbose_name='Establecimiento')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalRole',
            fields=[
                ('rol_id', models.IntegerField(blank=True, db_index=True)),
                ('role_name', models.CharField(db_index=True, max_length=50)),
                ('mantenedores', models.IntegerField(choices=[(0, 'Sin acceso'), (1, 'Solo lectura'), (2, 'Lectura y escritura')], default=0)),
                ('organizacion', models.IntegerField(choices=[(0, 'Sin acceso'), (1, 'Solo lectura'), (2, 'Lectura y escritura')], default=0)),
                ('plan', models.IntegerField(choices=[(0, 'Sin acceso'), (1, 'Solo lectura'), (2, 'Lectura y escritura')], default=0)),
                ('chip', models.IntegerField(choices=[(0, 'Sin acceso'), (1, 'Solo lectura'), (2, 'Lectura y escritura')], default=0)),
                ('celular', models.IntegerField(choices=[(0, 'Sin acceso'), (1, 'Solo lectura'), (2, 'Lectura y escritura')], default=0)),
                ('computador', models.IntegerField(choices=[(0, 'Sin acceso'), (1, 'Solo lectura'), (2, 'Lectura y escritura')], default=0)),
                ('toner', models.IntegerField(choices=[(0, 'Sin acceso'), (1, 'Solo lectura'), (2, 'Lectura y escritura')], default=0)),
                ('impresora', models.IntegerField(choices=[(0, 'Sin acceso'), (1, 'Solo lectura'), (2, 'Lectura y escritura')], default=0)),
                ('usuarios', models.IntegerField(choices=[(0, 'Sin acceso'), (1, 'Solo lectura'), (2, 'Lectura y escritura')], default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('establecimiento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='establecimiento.establecimiento')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Rol',
                'verbose_name_plural': 'historical Roles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalUser',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(db_index=True, max_length=200)),
                ('password', models.CharField(max_length=128)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('establecimiento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='establecimiento.establecimiento', verbose_name='Establecimiento')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Usuario',
                'verbose_name_plural': 'historical Usuarios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('rol_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50, unique=True)),
                ('mantenedores', models.IntegerField(choices=[(0, 'Sin acceso'), (1, 'Solo lectura'), (2, 'Lectura y escritura')], default=0)),
                ('organizacion', models.IntegerField(choices=[(0, 'Sin acceso'), (1, 'Solo lectura'), (2, 'Lectura y escritura')], default=0)),
                ('plan', models.IntegerField(choices=[(0, 'Sin acceso'), (1, 'Solo lectura'), (2, 'Lectura y escritura')], default=0)),
                ('chip', models.IntegerField(choices=[(0, 'Sin acceso'), (1, 'Solo lectura'), (2, 'Lectura y escritura')], default=0)),
                ('celular', models.IntegerField(choices=[(0, 'Sin acceso'), (1, 'Solo lectura'), (2, 'Lectura y escritura')], default=0)),
                ('computador', models.IntegerField(choices=[(0, 'Sin acceso'), (1, 'Solo lectura'), (2, 'Lectura y escritura')], default=0)),
                ('toner', models.IntegerField(choices=[(0, 'Sin acceso'), (1, 'Solo lectura'), (2, 'Lectura y escritura')], default=0)),
                ('impresora', models.IntegerField(choices=[(0, 'Sin acceso'), (1, 'Solo lectura'), (2, 'Lectura y escritura')], default=0)),
                ('usuarios', models.IntegerField(choices=[(0, 'Sin acceso'), (1, 'Solo lectura'), (2, 'Lectura y escritura')], default=0)),
                ('establecimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='establecimiento.establecimiento')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='HistoricalUserRole',
            fields=[
                ('user_role_id', models.IntegerField(blank=True, db_index=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('role_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.role')),
            ],
            options={
                'verbose_name': 'historical Rol del Usuario',
                'verbose_name_plural': 'historical Roles del Usuario',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('user_role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.role')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rol del Usuario',
                'verbose_name_plural': 'Roles del Usuario',
                'db_table': 'user_roles',
                'unique_together': {('user_id', 'role_id')},
            },
        ),
    ]
