# Generated by Django 6.0.1 on 2026-02-25 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='role_id',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='historicalrole',
            name='rol_id',
        ),
        migrations.RemoveField(
            model_name='role',
            name='rol_id',
        ),
        migrations.AddField(
            model_name='historicalrole',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, default=1, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='rol',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.role', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='role',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.role', verbose_name='Establecimiento'),
        ),
        migrations.DeleteModel(
            name='HistoricalUserRole',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
