# Generated by Django 6.0.1 on 2026-02-25 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userrole_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalrole',
            old_name='celular',
            new_name='equipos',
        ),
        migrations.RenameField(
            model_name='historicalrole',
            old_name='chip',
            new_name='soporte',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='celular',
            new_name='equipos',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='chip',
            new_name='soporte',
        ),
        migrations.RemoveField(
            model_name='historicalrole',
            name='computador',
        ),
        migrations.RemoveField(
            model_name='historicalrole',
            name='establecimiento',
        ),
        migrations.RemoveField(
            model_name='historicalrole',
            name='impresora',
        ),
        migrations.RemoveField(
            model_name='historicalrole',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='historicalrole',
            name='toner',
        ),
        migrations.RemoveField(
            model_name='role',
            name='computador',
        ),
        migrations.RemoveField(
            model_name='role',
            name='establecimiento',
        ),
        migrations.RemoveField(
            model_name='role',
            name='impresora',
        ),
        migrations.RemoveField(
            model_name='role',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='role',
            name='toner',
        ),
    ]
