# Generated by Django 6.0.1 on 2026-03-09 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0004_funcionario_puesto_trabajo_and_more'),
        ('users', '0003_rename_celular_historicalrole_equipos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='departamento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='establecimiento.departamento', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='usuario_soporte',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='establecimiento.departamento', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='user',
            name='usuario_soporte',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='rol',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.role', verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.role', verbose_name='Rol'),
        ),
    ]
