# Generated by Django 6.0.1 on 2026-03-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljefetic',
            name='posicion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jefetic',
            name='posicion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
