# Generated by Django 6.0.1 on 2026-06-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubcategoria',
            name='ver_informatica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalsubcategoria',
            name='ver_mantencion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='ver_informatica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='ver_mantencion',
            field=models.BooleanField(default=False),
        ),
    ]
