# Generated by Django 6.0.1 on 2026-03-13 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_historicalips_ips'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalips',
            old_name='estado',
            new_name='asignado',
        ),
        migrations.RenameField(
            model_name='ips',
            old_name='estado',
            new_name='asignado',
        ),
    ]
