# Generated by Django 6.0.1 on 2026-04-28 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_initial'),
        ('equipo', '0001_initial'),
        ('establecimiento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionip',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por'),
        ),
        migrations.AddField(
            model_name='asignacionip',
            name='ip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_ip', to='catalogo.ips', verbose_name='Dirección IP'),
        ),
        migrations.AddField(
            model_name='asignacionip',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado Por'),
        ),
        migrations.AddField(
            model_name='celular',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='celular_contrato', to='catalogo.contrato'),
        ),
        migrations.AddField(
            model_name='celular',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por'),
        ),
        migrations.AddField(
            model_name='celular',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='celular_departamento', to='establecimiento.departamento'),
        ),
        migrations.AddField(
            model_name='celular',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='celular_establecimiento', to='establecimiento.establecimiento'),
        ),
        migrations.AddField(
            model_name='celular',
            name='jefe_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='celular_jefetic', to='catalogo.jefetic'),
        ),
        migrations.AddField(
            model_name='celular',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.marca'),
        ),
        migrations.AddField(
            model_name='celular',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.modelo'),
        ),
        migrations.AddField(
            model_name='celular',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='celular_propietario', to='catalogo.propietario'),
        ),
        migrations.AddField(
            model_name='celular',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='celular_responsable', to='establecimiento.funcionario'),
        ),
        migrations.AddField(
            model_name='celular',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.tipocelular'),
        ),
        migrations.AddField(
            model_name='celular',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado Por'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.contrato'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='establecimiento.departamento'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='establecimiento.establecimiento'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='ip',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo', to='catalogo.ips'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='jefe_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.jefetic'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.marca'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='microsoft_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.microsoftoffice'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.modelo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.propietario'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='establecimiento.funcionario'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='sistema_operativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.sistemaoperativo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='tipo_impresora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.tipoimpresora'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='tipo_pc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.tipocomputador'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='toner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.toner'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado Por'),
        ),
        migrations.AddField(
            model_name='asignacionip',
            name='equipo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_ip', to='equipo.equipo', verbose_name='Equipo'),
        ),
        migrations.AddField(
            model_name='historicalasignacionip',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por'),
        ),
        migrations.AddField(
            model_name='historicalasignacionip',
            name='equipo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='equipo.equipo', verbose_name='Equipo'),
        ),
        migrations.AddField(
            model_name='historicalasignacionip',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalasignacionip',
            name='ip',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogo.ips', verbose_name='Dirección IP'),
        ),
        migrations.AddField(
            model_name='historicalasignacionip',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado Por'),
        ),
        migrations.AddField(
            model_name='historicalcelular',
            name='contrato',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogo.contrato'),
        ),
        migrations.AddField(
            model_name='historicalcelular',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por'),
        ),
        migrations.AddField(
            model_name='historicalcelular',
            name='departamento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='establecimiento.departamento'),
        ),
        migrations.AddField(
            model_name='historicalcelular',
            name='establecimiento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='establecimiento.establecimiento'),
        ),
        migrations.AddField(
            model_name='historicalcelular',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcelular',
            name='jefe_entrega',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogo.jefetic'),
        ),
        migrations.AddField(
            model_name='historicalcelular',
            name='marca',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogo.marca'),
        ),
        migrations.AddField(
            model_name='historicalcelular',
            name='modelo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogo.modelo'),
        ),
        migrations.AddField(
            model_name='historicalcelular',
            name='propietario',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogo.propietario'),
        ),
        migrations.AddField(
            model_name='historicalcelular',
            name='responsable',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='establecimiento.funcionario'),
        ),
        migrations.AddField(
            model_name='historicalcelular',
            name='tipo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogo.tipocelular'),
        ),
        migrations.AddField(
            model_name='historicalcelular',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado Por'),
        ),
        migrations.AddField(
            model_name='historicalequipo',
            name='contrato',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogo.contrato'),
        ),
        migrations.AddField(
            model_name='historicalequipo',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por'),
        ),
        migrations.AddField(
            model_name='historicalequipo',
            name='departamento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='establecimiento.departamento'),
        ),
        migrations.AddField(
            model_name='historicalequipo',
            name='establecimiento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='establecimiento.establecimiento'),
        ),
        migrations.AddField(
            model_name='historicalequipo',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalequipo',
            name='ip',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogo.ips'),
        ),
        migrations.AddField(
            model_name='historicalequipo',
            name='jefe_entrega',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogo.jefetic'),
        ),
        migrations.AddField(
            model_name='historicalequipo',
            name='marca',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogo.marca'),
        ),
        migrations.AddField(
            model_name='historicalequipo',
            name='microsoft_office',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogo.microsoftoffice'),
        ),
        migrations.AddField(
            model_name='historicalequipo',
            name='modelo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogo.modelo'),
        ),
        migrations.AddField(
            model_name='historicalequipo',
            name='propietario',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogo.propietario'),
        ),
        migrations.AddField(
            model_name='historicalequipo',
            name='responsable',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='establecimiento.funcionario'),
        ),
        migrations.AddField(
            model_name='historicalequipo',
            name='sistema_operativo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogo.sistemaoperativo'),
        ),
        migrations.AddField(
            model_name='historicalequipo',
            name='tipo_impresora',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogo.tipoimpresora'),
        ),
        migrations.AddField(
            model_name='historicalequipo',
            name='tipo_pc',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogo.tipocomputador'),
        ),
        migrations.AddField(
            model_name='historicalequipo',
            name='toner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogo.toner'),
        ),
        migrations.AddField(
            model_name='historicalequipo',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado Por'),
        ),
    ]
