# Generated by Django 6.0.1 on 2026-02-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computador',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcomputador',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
