# Generated by Django 6.0.1 on 2026-02-25 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_initial'),
        ('equipo', '0002_computador_observaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computador',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computador_contrato', to='catalogo.contrato'),
        ),
        migrations.AlterField(
            model_name='historicalcomputador',
            name='contrato',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogo.contrato'),
        ),
    ]
