# Generated by Django 6.0.1 on 2026-03-09 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0005_computador_establecimiento_and_more'),
        ('establecimiento', '0005_departamento_alias_historicaldepartamento_alias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalimpresora',
            name='establecimiento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='establecimiento.establecimiento'),
        ),
        migrations.AddField(
            model_name='impresora',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impresora_establecimiento', to='establecimiento.establecimiento'),
        ),
    ]
