# Generated by Django 6.0.1 on 2026-03-30 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_rename_estado_historicalips_asignado_and_more'),
        ('equipo', '0006_historicalimpresora_establecimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computador',
            name='ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.ips'),
        ),
        migrations.AlterField(
            model_name='historicalcomputador',
            name='ip',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogo.ips'),
        ),
    ]
