# Generated by Django 6.0.1 on 2026-03-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0007_alter_computador_ip_alter_historicalcomputador_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='celular',
            name='asignado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='computador',
            name='asignado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcelular',
            name='asignado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcomputador',
            name='asignado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalimpresora',
            name='asignado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='impresora',
            name='asignado',
            field=models.BooleanField(default=False),
        ),
    ]
