# Generated by Django 6.0.1 on 2026-03-05 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_historicalpuestotrabajo_puestotrabajo'),
        ('establecimiento', '0003_departamento_funcionario_historicaldepartamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='puesto_trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.puestotrabajo', verbose_name='Puesto de Trabajo'),
        ),
        migrations.AddField(
            model_name='historicalfuncionario',
            name='puesto_trabajo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogo.puestotrabajo', verbose_name='Puesto de Trabajo'),
        ),
    ]
