# Generated by Django 6.0.1 on 2026-03-09 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0004_funcionario_puesto_trabajo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='alias',
            field=models.CharField(default='NO INFORMADO', max_length=100, verbose_name='Alias del Departamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldepartamento',
            name='alias',
            field=models.CharField(default='NO INFORMADO', max_length=100, verbose_name='Alias del Departamento'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='departamento',
            constraint=models.UniqueConstraint(fields=('nombre', 'establecimiento'), name='unique_departamento_por_establecimiento'),
        ),
    ]
