# Generated by Django 6.0.1 on 2026-03-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0005_departamento_alias_historicaldepartamento_alias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='alias',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alias del Establecimiento'),
        ),
        migrations.AddField(
            model_name='historicalestablecimiento',
            name='alias',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alias del Establecimiento'),
        ),
    ]
