# Generated by Django 6.0.1 on 2026-02-03 18:01

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalfuncionario',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='jefatura',
            name='departamentp',
        ),
        migrations.RemoveField(
            model_name='historicaljefatura',
            name='departamentp',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='historicaldepartamento',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicaldepartamento',
            name='establecimiento',
        ),
        migrations.RemoveField(
            model_name='historicaldepartamento',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldepartamento',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='historicalfuncionario',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalfuncionario',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalfuncionario',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='historicaljefatura',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicaljefatura',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaljefatura',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='jefatura',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='jefatura',
            name='updated_by',
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado Por')),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
            },
        ),
        migrations.CreateModel(
            name='HistoricalComuna',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Última Actualización')),
                ('nombre', models.CharField(db_index=True, max_length=100, verbose_name='Nombre')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado Por')),
            ],
            options={
                'verbose_name': 'historical Comuna',
                'verbose_name_plural': 'historical Comunas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
        migrations.DeleteModel(
            name='HistoricalDepartamento',
        ),
        migrations.DeleteModel(
            name='HistoricalFuncionario',
        ),
        migrations.DeleteModel(
            name='HistoricalJefatura',
        ),
        migrations.DeleteModel(
            name='Jefatura',
        ),
    ]
