# Generated by Django 6.0.1 on 2026-02-03 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0003_remove_historicalfuncionario_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='comuna',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='establecimiento.comuna', verbose_name='Comuna'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='historicalestablecimiento',
            name='comuna',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='establecimiento.comuna', verbose_name='Comuna'),
        ),
        migrations.AddField(
            model_name='historicalestablecimiento',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='historicalestablecimiento',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono'),
        ),
    ]
