# Generated by Django 6.0.1 on 2026-02-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0005_departamento_historicaldepartamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='historicaldepartamento',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección'),
        ),
    ]
