# Generated by Django 6.0.1 on 2026-03-11 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_solicitante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalticket',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='historicalticket',
            name='solicitante',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='solicitante',
        ),
    ]
