# Generated by Django 6.0.1 on 2026-03-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_historicalticket_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticket',
            name='departamento',
            field=models.CharField(default='NO INFORMADO', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='departamento',
            field=models.CharField(default='NO INFORMADO', max_length=20),
        ),
    ]
