# Generated by Django 6.0.1 on 2026-03-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_historicalticket_departamento_ticket_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticket',
            name='solucion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='solucion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
