# Generated by Django 6.0.1 on 2026-03-12 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('establecimiento', '0005_departamento_alias_historicaldepartamento_alias_and_more'),
        ('tickets', '0006_data_migrate_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticket',
            name='establecimiento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='establecimiento.establecimiento'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='tickets', to='establecimiento.establecimiento'),
        ),
        migrations.AlterField(
            model_name='historicalticket',
            name='departamento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='establecimiento.departamento'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='tickets', to='establecimiento.departamento'),
        ),
    ]
