# Generated by Django 6.0.1 on 2026-03-13 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_historicalpuestotrabajo_puestotrabajo'),
        ('tickets', '0006_historicalticket_establecimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticket',
            name='tipo_soporte',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogo.tiposoporte'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tipo_soporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipo_soporte', to='catalogo.tiposoporte'),
        ),
    ]
