# Generated by Django 6.0.1 on 2026-03-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_historicalticket_tipo_soporte_ticket_tipo_soporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
