# Generated by Django 6.0.1 on 2026-03-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_alter_historicalticket_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
