# Generated by Django 6.0.1 on 2026-03-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_ticketactivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='numero_ticket',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='numero_ticket',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
