# Generated by Django 6.0.1 on 2026-04-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_alter_historicalticket_numero_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticket',
            name='area_soporte',
            field=models.CharField(blank=True, choices=[('Mantencion', 'Mantencion'), ('Informatica', 'Informatica')], null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='area_soporte',
            field=models.CharField(blank=True, choices=[('Mantencion', 'Mantencion'), ('Informatica', 'Informatica')], null=True),
        ),
    ]
