# Generated by Django 6.0.1 on 2026-04-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_historicalticket_area_soporte_ticket_area_soporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='area_soporte',
            field=models.CharField(blank=True, choices=[('MANTENCION', 'Mantencion'), ('INFORMATICA', 'Informatica')], null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='area_soporte',
            field=models.CharField(blank=True, choices=[('MANTENCION', 'Mantencion'), ('INFORMATICA', 'Informatica')], null=True),
        ),
    ]
